<div id="project-content" data-user-id="<?php echo isset($_SESSION['user_id']) ? $_SESSION['user_id'] : ''; ?> data-role="<?php echo isset($_SESSION['role']) ? $_SESSION['role'] : ''; ?>">
    <div class="project-intro">
        <div class="project-txt">
            <p>All Projects</p>
            <p>View all your assigned projects below. Statistics about these are within.</p>
        </div>
        <?php if (isset($_SESSION['role']) && $_SESSION['role'] === 'manager'): ?>
            <a href="#" class="add-project black-btn">Add Project</a>
        <?php endif; ?>
        
    </div>

    <div class="grid-container" id="gridContainer">
        <!-- Project Cards dynamically generated by JS -->
        <!--Hardcoded Project Card with Crown icon for Demo-->
        <?php if (isset($_SESSION['role']) && $_SESSION['role'] === 'leader'): ?>
         <div class="project-card" id="leader-project-card">
            <div class="project-card-top">
                <div class="project-card-top-left">
                    <i class="fa fa-solid fa-crown"></i>
                    <p>Python Project</p>
                </div>
                    <a href="#" class="black-btn">View</a>
                </div>
                <div class="project-card-progress">
                    <div class="project-card-progress-info">
                        <p>Progress</p>
                        <p>75%</p>
                    </div>
                    <div class="project-card-progress-bar">
                        <div class="project-card-progress-bar-inner" style="width: 75%; background-color: #ADDA9D;"></div>
                    </div>
                </div>

                <div class="project-card-bottom">
                    <div class="project-card-team">
                        <div class="project-user"><i class="fa fa-solid fa-user"></i></div>
                        <div class="project-user"><i class="fa fa-solid fa-user"></i></div>
                        <div class="project-user"><i class="fa fa-solid fa-user"></i></div>
                        <div class="project-user"><i class="fa fa-solid fa-user"></i></div>
                        <div class="project-user">+3</div>
                    </div>
                    <div class="project-card-due-date">
                        <i class="fa fa-regular fa-calendar"></i>
                        <p>21 Nov</p>
                    </div>
                </div>
         </div>
         <?php endif; ?>
    </div>


        <!--Filter Posts -->
        <div id="projects-modal" class="modal">
            <div class="modal-box">
                <!--Header-->
                <div class="modal-header">
                    <p>Add Project</p>
                    <div class="close-modal-btn">
                        <i class="fa-solid fa-x"></i>
                    </div>
                </div>
                <!--Body-->
                
                <form id="project-modal-form" class="modal-body">
                    <!--Title and Description-->
                    <div class="task-title-form">
                        <label for="task-title">Title</label>
                        <input type="text" id="task-title" name="task-title">
                    </div>
                    <div class="task-description-form">
                        <label for="task-description">Description</label>
                        <textarea type="text" id="task-description" name="task-description"></textarea>
                    </div>
                    <div class="task-dropdowns-form" id="project-dropdowns-form" style="margin: 2rem;">
                        <!--DropDown Leader-->
                        <div class="task-dropdown task-dropdown-leader">
                            <label for="team-leader">Team Leader</label>
                            <div class="task-dropdown-select-options">
                                <div class="task-dropdown-user-icon task-dropdown-icon">
                                    <i class="fa fa-solid fa-user"></i>
                                </div>
                                <select name="team-leader" id="team-leader">
                                    <option value="choose" selected disabled hidden>Choose</option>
                                    <option value="jlittle">John Little</option>
                                    <option value="jganatra">Jeevan Ganatra</option>
                                    <option value="dnovetsky">Daniel Novetsky</option>
                                    <option value="supreti">Sawan Upreti</option>
                                    <option value="high">High</option>
                                    <option value="stuck">Stuck</option>
                                </select>
                            </div>  
                        </div>
                    
                        <!--Choose Due Date-->
                        <div class="task-dropdown task-dropdown-date">
                            <label for="date">Due Date</label>
                            <div class="task-dropdown-select-options">
                                <div class="task-dropdown-date-icon task-dropdown-icon">
                                    <i class="fa fa-regular fa-calendar"></i>
                                </div>
                                <input type="date" name="date" id="date">
                            </div>  
                        </div>
                    </div>
                </form>
                <div class="task-submit-buttons">
                    <div class="add-project-btn" id="add-project-btn">
                        Create Project
                        <i class="fa fa-arrow-right"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>



</div>
