<div id="project-content" data-user-id="<?php echo isset($_SESSION['user_id']) ? $_SESSION['user_id'] : ''; ?> data-role="<?php echo isset($_SESSION['role']) ? $_SESSION['role'] : ''; ?>">
    <div class="project-intro">
        <div class="project-txt">
            <p>All Projects</p>
            <p>View all your assigned projects below. Statistics about these are within.</p>
        </div>
     
        <?php if (isset($_SESSION['role']) && $_SESSION['role'] === 'manager'): ?>
            <a href="#" class="add-project black-btn">Add Project</a>
        <?php endif; ?>
        
    </div>
    <div class="project-filter-container">
        <div class="project-search">
            <i class="fa fa-solid fa-search"></i>
            <input type="text" placeholder="Search Projects" id="searched-project">
        </div>
        <div class="filter-project-btn black-btn"> Filter
            <i class="fa fa-solid fa-sliders"></i>
        </div>
    </div>

    <p class="search-error-msg">No Projects Found</p>
    <div class="grid-container" id="gridContainer">
        <!-- Project Cards dynamically generated by JS -->
        <!--Hardcoded Project Card with Crown icon for Demo-->
      
    </div>

      <!--Filter Projects -->
      <div id="project-filter-modal" class="modal">
        <div class="modal-box">
            <!--Header-->
            <div class="modal-header">
                <p>Filter Projects</p>
                <div class="close-modal-btn">
                    <i class="fa-solid fa-x"></i>
                </div>
            </div>
            <!--Body-->
            <form id="filter-modal-form" class="modal-body">
                <div class="task-dropdowns-form" id="post-dropdowns-form">
                   
                
                    <!--DropDown 1-->
                    <div class="task-dropdown task-dropdown-priority">
                        <label for="priority">Priority</label>
                        <div class="task-dropdown-select-options">
                            <div class="task-dropdown-priority-icon task-dropdown-icon">
                                <i class="fa fa-solid fa-star"></i>
                            </div>
                            <select name="priority" id="priority">
                                <option value="All">All</option>
                                <option value="None">None</option>
                                <option value="Low">Low</option>
                                <option value="Medium">Medium</option>
                                <option value="High">High</option>
                            </select>
                        </div>
                    </div>
                    <!--DropDown 2-->
                    <div class="task-dropdown task-dropdown-date">
                        <label for="date">Due Date</label>
                        <div class="task-dropdown-select-options">
                            <div class="task-dropdown-date-icon task-dropdown-icon">
                                <i class="fa fa-solid fa-calendar-days"></i>
                            </div>
                            <select name="date" id="date-task">
                                <option value="All">All</option>
                                <option value="Today">Today</option>
                                <option value="Tomorrow">Tomorrow</option>
                                <option value="This Week">This Week</option>
                                <option value="Next Week">Next Week</option>
                                <option value="Later">Later</option>
                            </select>
                        </div>
                    </div>

                </div>
            </form>
            <div class="task-submit-buttons">
                <a class="add-filter-btn" id="add-filter-btn">
                    Filter Projects
                    <i class="fa fa-arrow-right"></i>
                </a>
            </div>
        </div>
    </div>



        <!--Filter Posts -->
        <div id="projects-modal" class="modal">
            <div class="modal-box">
                <!--Header-->
                <div class="modal-header">
                    <p>Add Project</p>
                    <div class="close-modal-btn">
                        <i class="fa-solid fa-x"></i>
                    </div>
                </div>
                <!--Body-->
                
                <form id="project-modal-form" class="modal-body">
                    <!--Title and Description-->
                    <div class="task-title-form">
                        <label for="task-title">Title</label>
                        <input type="text" id="task-title" name="task-title">
                    </div>
                    <div class="task-description-form">
                        <label for="task-description">Description</label>
                        <textarea type="text" id="task-description" name="task-description"></textarea>
                    </div>
                    <div class="task-dropdowns-form" id="project-dropdowns-form" style="margin: 2rem;">
                        <!--DropDown Leader-->
                        <div class="task-dropdown task-dropdown-leader">
                            <label for="team-leader">Team Leader</label>
                            <div class="task-dropdown-select-options">
                                <div class="task-dropdown-user-icon task-dropdown-icon">
                                    <i class="fa fa-solid fa-user"></i>
                                </div>
                                <select name="team-leader" id="team-leader">
                                    <option value="choose" selected disabled hidden>Choose</option>
                                    <option value="jlittle">John Little</option>
                                    <option value="jganatra">Jeevan Ganatra</option>
                                    <option value="dnovetsky">Daniel Novetsky</option>
                                    <option value="supreti">Sawan Upreti</option>
                                    <option value="high">High</option>
                                    <option value="stuck">Stuck</option>
                                </select>
                            </div>  
                        </div>
                    
                        <!--Choose Due Date-->
                        <div class="task-dropdown task-dropdown-date">
                            <label for="date">Due Date</label>
                            <div class="task-dropdown-select-options">
                                <div class="task-dropdown-date-icon task-dropdown-icon">
                                    <i class="fa fa-regular fa-calendar"></i>
                                </div>
                                <input type="date" name="date" id="date-project">
                            </div>  
                        </div>
                    </div>
                </form>
                <div class="task-submit-buttons">
                    <div class="add-project-btn" id="add-project-btn">
                        Create Project
                        <i class="fa fa-arrow-right"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
  
</div>
