<div class="project-intro">
    <div class="project-txt">
        <p>All Projects</p>
        <p>View all your assigned projects below. Statistics about these are within.</p>
    </div>
</div>

<div class="grid-container" id="gridContainer">
    <!-- Grid items will be dynamically generated by JS -->
</div>
