<div class="project-intro">
    <div class="project-txt">
        <p>All Projects</p>
        <p>View all your assigned projects below. Statistics about these are within.</p>
    </div>
    <?php if (isset($_SESSION['role']) && $_SESSION['role'] === 'manager'): ?>
        <a href="#">Add Project</a>
    <?php endif; ?>
    
</div>

<div class="grid-container" id="gridContainer">
    <!-- Project Cards dynamically generated by JS -->
</div>
